# Generated by Django 6.0.3 on 2026-06-20 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_perfilusuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='ciudad',
            options={'verbose_name': 'Ciudad', 'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name_plural': 'Colores'},
        ),
        migrations.AlterModelOptions(
            name='lineapedido',
            options={'verbose_name': 'Detalle de Pedido', 'verbose_name_plural': 'Detalles de Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={},
        ),
        migrations.RenameField(
            model_name='lineapedido',
            old_name='creado_en',
            new_name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='ciudad',
            name='costo_envio',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='contacto_proveedor',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='direccion',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Categoría'),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='departamento',
            field=models.CharField(max_length=100, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre de la Ciudad/Municipio'),
        ),
        migrations.AlterField(
            model_name='color',
            name='codigo_hex',
            field=models.CharField(default='#000000', max_length=7, verbose_name='Código Hexadecimal'),
        ),
        migrations.AlterField(
            model_name='color',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre del Color'),
        ),
        migrations.AlterField(
            model_name='lineapedido',
            name='cantidad',
            field=models.IntegerField(default=1, verbose_name='Cantidad Comprada'),
        ),
        migrations.AlterField(
            model_name='lineapedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='tienda.pedido'),
        ),
        migrations.AlterField(
            model_name='lineapedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto', verbose_name='Prenda'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Marca'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='ciudad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.ciudad', verbose_name='Ciudad de Destino'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='completado',
            field=models.BooleanField(default=False, verbose_name='¿Entregado y Cerrado?'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='direccion_exacta',
            field=models.CharField(max_length=255, verbose_name='Dirección de Envío'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PEN', 'Pendiente de Pago'), ('PRE', 'En Preparación'), ('ENV', 'Enviado'), ('ENT', 'Entregado'), ('CAN', 'Cancelado')], default='PEN', max_length=3, verbose_name='Estado del Pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Compra'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Pagado'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('ADM', 'Administrador'), ('EMP', 'Empleado / Vendedor'), ('CLI', 'Cliente')], default='CLI', max_length=3, verbose_name='Rol en la plataforma'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='tienda.categoria', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.color', verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='disponible',
            field=models.BooleanField(default=True, verbose_name='Disponible para la venta'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen del Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.marca', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre del Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=10, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Cantidad en Stock'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='talla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.talla', verbose_name='Talla'),
        ),
        migrations.AlterField(
            model_name='talla',
            name='nombre',
            field=models.CharField(max_length=10, unique=True, verbose_name='Talla'),
        ),
        migrations.DeleteModel(
            name='Calificacion',
        ),
    ]
